apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/instance: observatorium-xyz
    app.kubernetes.io/name: dex
    app.kubernetes.io/version: v2.24.0
  name: dex
  namespace: dex
stringData:
  config.yaml: |-
    connectors:
    - config:
        clientID: system:serviceaccount:dex:dex-server
        clientSecret: 
        insecureCA: true
        issuer: https://kubernetes.default.svc
        redirectURI: http://127.0.0.1:5556/dex/
      id: openshift
      name: OpenShift
      type: openshift
    grpc:
      addr: 0.0.0.0:5557
    "enablePasswordDB": true
    "issuer": "https://dex.dex.svc.cluster.local:5556/dex"
    "logger":
      "level": "debug"
    "oauth2":
      "passwordConnector": "local"
    "staticClients":
    - "id": "test"
      "issuerCAPath": "/var/run/tls/test/service-ca.crt"
      "name": "test"
      "secret": "ZXhhbXBsZS1hcHAtc2VjcmV0"
    "staticPasswords":
    - "email": "admin@example.com"
      "hash": "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      "userID": "08a8684b-db88-4b73-90a9-3cd1661f5466"
      "username": "admin"
    "storage":
      "config":
        "file": "/storage/dex.db"
      "type": "sqlite3"
    "web":
      "https": "0.0.0.0:5556"
      "tlsCert": "/etc/dex/tls/tls.crt"
      "tlsKey": "/etc/dex/tls/tls.key"
    telemetry:
      http: 0.0.0.0:5558
