apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
  namespace: observatorium
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: <YOUR-BUCKET-NAME>
      endpoint: s3.openshift-storage.svc:443
      insecure: true
      access_key: <YOUR-ACCESS-KEY>
      secret_key: <YOUR-SECRET-KEY>
type: Opaque
